/* this file is automatically generated by garbanzo */
/* DO NOT MANUALLY EDIT THIS FILE */

import { createPages } from "waku";
import type { PathsForPages } from "waku/router";

import layout0 from "./app/@layout";
import root1 from "./app/@root";
import page2 from "./app/about/page";
import route3 from "./app/api/greet/route";
import page4 from "./app/episodes/1/vibe-coding-when-the-vibes-are-off/page";
import page5 from "./app/episodes/2/is-the-web-getting-worse/page";
import page6 from "./app/episodes/3/a-day-in-the-life-coding-coffee-and-commit-messages/page";
import page7 from "./app/episodes/4/perfecting-the-pull-request/page";
import page8 from "./app/episodes/page";
import page9 from "./app/page";
import route10 from "./app/rss.xml/route";
import page11 from "./app/search/page";

let pages = createPages(async ({ createPage, createLayout, createRoot, createApi }) => [
createLayout({
  render: "dynamic",
  path: "/",
  component: layout0,
}),
createRoot({
  render: "dynamic",
  component: root1,
}),
createPage({
  render: "dynamic",
  path: "/about",
  component: page2,
}),
createApi({
  render: "dynamic",
  path: "/api/greet",
  handlers: {
    GET: route3,
    POST: route3,
    PUT: route3,
    DELETE: route3,
    PATCH: route3,
    OPTIONS: route3,
    HEAD: route3,
    TRACE: route3,
    CONNECT: route3,
  },
}),
createPage({
  render: "dynamic",
  path: "/episodes/1/vibe-coding-when-the-vibes-are-off",
  component: page4,
}),
createPage({
  render: "dynamic",
  path: "/episodes/2/is-the-web-getting-worse",
  component: page5,
}),
createPage({
  render: "dynamic",
  path: "/episodes/3/a-day-in-the-life-coding-coffee-and-commit-messages",
  component: page6,
}),
createPage({
  render: "dynamic",
  path: "/episodes/4/perfecting-the-pull-request",
  component: page7,
}),
createPage({
  render: "dynamic",
  path: "/episodes",
  component: page8,
}),
createPage({
  render: "dynamic",
  path: "/",
  component: page9,
}),
createApi({
  render: "dynamic",
  path: "/rss.xml",
  handlers: {
    GET: route10,
    POST: route10,
    PUT: route10,
    DELETE: route10,
    PATCH: route10,
    OPTIONS: route10,
    HEAD: route10,
    TRACE: route10,
    CONNECT: route10,
  },
}),
createPage({
  render: "dynamic",
  path: "/search",
  component: page11,
}),
]);

declare module "waku/router" {
  interface RouteConfig {
    paths: PathsForPages<typeof pages>;
  }
  interface CreatePagesConfig {
    pages: typeof pages;
  }
}

export default pages;